Algoritmo "for"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 9/9/2020
Var
// Seção de Declarações das variáveis 
   c, n, s: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para c <- 1 ate 5 passo 1 faça
       escreval("Digite um valor: ")
       leia(n)
       s <- s + n
   fimpara
   escreva("A soma dos valores e ", s)
   
   
Fimalgoritmo