Algoritmo "soma"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 9/9/2020
Var
   conta, soma, num: inteiro


Inicio
      escreva("Escolha um numero da tabuada de 10:")
      leia(conta)
      num <- 0
      enquanto (num < 10) faca
          num <- num + 1
          soma <- conta * num
          escreval(conta," x", num , " =", soma)
      fimenquanto


Fimalgoritmo